'LekaOS Project Management':
  'Backlog':
    - '99 - status: backlog'
  'To do':
    - '99 - status: to do'
  'In progress':
    - '99 - status: in progress'
  'Review needed':
    - '99 - status: review needed'
  'Review approved':
    - '99 - status: review approved'
  'Done':
    - '99 - status: done'
