version: "2"
exclude_patterns:
  - ".github"
  - "extern/mbed-os"
  - "targets"
  - "tests/unit/mbed-os"
  - "tools/target_generator.py"
  - "tools/run-clang-format.py"
  - "cmake/scripts/configure_cmake_for_target.py"

plugins:
  markdownlint:
    enabled: true
