plugins:
  cppcheck:
    enabled: true
    config:
      check: all
      project: compile_commands.json
      language: c++
      stds:
        - c++14
      platform: unix32
      max_configs: 42
      inconclusive: true
      suppressions-list: .cppcheck_suppressions
      inline-suppr: true
