// Leka - LekaOS
// Copyright 2020 APF France handicap
// SPDX-License-Identifier: Apache-2.0

#define ARM_MATH_CM7			   1
#define COMPONENT_BlueNRG_MS	   1
#define COMPONENT_FLASHIAP		   1
#define COMPONENT_SD			   1
#define DEVICE_ANALOGIN			   1
#define DEVICE_ANALOGOUT		   1
#define DEVICE_CRC				   1
#define DEVICE_FLASH			   1
#define DEVICE_I2C				   1
#define DEVICE_I2C_ASYNCH		   1
#define DEVICE_INTERRUPTIN		   1
#define DEVICE_LPTICKER			   1
#define DEVICE_MPU				   1
#define DEVICE_PORTIN			   1
#define DEVICE_PORTINOUT		   1
#define DEVICE_PORTOUT			   1
#define DEVICE_PWMOUT			   1
#define DEVICE_QSPI				   1
#define DEVICE_RESET_REASON		   1
#define DEVICE_RTC				   1
#define DEVICE_SERIAL			   1
#define DEVICE_SERIAL_ASYNCH	   1
#define DEVICE_SERIAL_FC		   1
#define DEVICE_SLEEP			   1
#define DEVICE_SPI				   1
#define DEVICE_SPI_ASYNCH		   1
#define DEVICE_STDIO_MESSAGES	   1
#define DEVICE_TRNG				   1
#define DEVICE_USTICKER			   1
#define DEVICE_WATCHDOG			   1
#define EXTRA_IDLE_STACK_REQUIRED  1
#define FEATURE_BLE				   1
#define HSE_VALUE				   25000000
#define MBED_BUILD_TIMESTAMP	   1609854094.263537
#define MBED_TICKLESS			   1
#define STM32F769xx				   1
#define TARGET_CORDIO			   1
#define TARGET_CORTEX			   1
#define TARGET_CORTEX_M			   1
#define TARGET_LEKA_Vx_x_UNIT_TEST 1
#define TARGET_LIKE_CORTEX_M7	   1
#define TARGET_LIKE_MBED		   1
#define TARGET_M7				   1
#define TARGET_MCU_STM32		   1
#define TARGET_MCU_STM32F7		   1
#define TARGET_NAME				   LEKA_Vx_x_UNIT_TEST
#define TARGET_RELEASE			   1
#define TARGET_RTOS_M4_M7		   1
#define TARGET_STM				   1
#define TARGET_STM32F7			   1
#define TARGET_STM32F769xI		   1
#define TOOLCHAIN_GCC			   1
#define TOOLCHAIN_GCC_ARM		   1
#define TRANSACTION_QUEUE_SIZE_SPI 2
#define USE_FULL_LL_DRIVER		   1
#define USE_HAL_DRIVER			   1
#define __CMSIS_RTOS			   1
#define __CORTEX_M7				   1
#define __FPU_PRESENT			   1
#define __MBED_CMSIS_RTOS_CM	   1
#define FEATURE_EXPERIMENTAL_API   1
