# Leka - LekaOS
# Copyright 2022 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Code Analysis - Sanitizers

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_sanitizers:
    name: Build & run
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            optimisation_level: "-Og"
            compiler:
              name: GCC 10
              cc: /usr/bin/gcc-10
              cxx: /usr/bin/g++-10

          - os: ubuntu-22.04
            optimisation_level: "-Os"
            compiler:
              name: GCC 10
              cc: /usr/bin/gcc-10
              cxx: /usr/bin/g++-10

          - os: ubuntu-24.04
            optimisation_level: "-Og"
            compiler:
              name: Clang 18
              cc: /usr/bin/clang-18
              cxx: /usr/bin/clang++-18

          - os: ubuntu-24.04
            optimisation_level: "-Os"
            compiler:
              name: Clang 18
              cc: /usr/bin/clang-18
              cxx: /usr/bin/clang++-18

          - os: ubuntu-24.04
            optimisation_level: "-Og"
            compiler:
              name: GCC 13
              cc: /usr/bin/gcc-13
              cxx: /usr/bin/g++-13

          - os: ubuntu-24.04
            optimisation_level: "-Os"
            compiler:
              name: GCC 13
              cc: /usr/bin/gcc-13
              cxx: /usr/bin/g++-13

    steps:
      - uses: actions/checkout@v4

      - name: Set CC & CXX env
        id: set_cc_cxx_env
        shell: bash
        run: |
          ${{ matrix.compiler.cc }} --version
          ${{ matrix.compiler.cxx }} --version
          echo "CC=${{ matrix.compiler.cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.compiler.cxx }}" >> $GITHUB_ENV

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          mbed_os_version: "head_version"
          ccache_key: ${{ runner.os }}-ccache-code_analysis-sanitizers-(${{ matrix.compiler.name }})-(${{ matrix.optimisation_level }})
          ccache_restore_keys: |
            ${{ runner.os }}-ccache-code_analysis-sanitizers-(${{ matrix.compiler.name }})-(${{ matrix.optimisation_level }})-
            ${{ runner.os }}-ccache-code_analysis-sanitizers-(${{ matrix.compiler.name }})-
            ${{ runner.os }}-ccache-code_analysis-sanitizers-
            ${{ runner.os }}-ccache-code_analysis-
            ${{ runner.os }}-ccache-

      #
      # Mark: - Config, build & run unit tests
      #

      - name: Ccache pre build
        run: |
          make ccache_prebuild

      - name: Config, build & run
        run: |
          export ASAN_OPTIONS=detect_leaks=1
          export UBSAN_OPTIONS=print_stacktrace=1
          make config_unit_tests COVERAGE=ON SANITIZERS=ON CI_UT_OPTIMIZATION_LEVEL="${{ matrix.optimisation_level }}"
          make unit_tests

      - name: Ccache post build
        run: |
          make ccache_postbuild
          cat ${{ env.CCACHE_LOGFILE }} || True
          ccache -z
