# Leka - LekaOS
# Copyright 2021 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Code Analysis

on:
  push:
    branches:
      - master
      - develop
    paths:
      - ".gcc_arm_none_eabi_url"

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".gcc_arm_none_eabi_url"

env:
  CC: /usr/bin/gcc
  CXX: /usr/bin/g++

  CLICOLOR_FORCE: true # ninja

  CCACHE_DIR: /home/runner/work/ccache
  CCACHE_COMPRESS: true
  CCACHE_COMPRESSLEVEL: 6

  ARM_TOOLCHAIN_FILENAME: "gcc-arm-none-eabi-*-x86_64-linux.tar.bz2"
  ARM_TOOLCHAIN_EXTRACT_DIRECTORY: "gcc-arm-none-eabi-*"

jobs:
  update_arm_toolchain:
    name: Update GNU Arm Embedded Toolchain
    runs-on: ubuntu-latest

    steps:
      #
      # Mark: - Setup
      #
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          ccache_name: code_analysis-update_arm_toolchain

      #
      # Mark: - Download toolchains
      #

      - name: Create toolchain url variables
        id: create_toolchain_url_variables
        run: |
          git checkout ${{ env.BASE_REF }}
          echo "BASE_TOOLCHAIN_URL=$(cat .gcc_arm_none_eabi_url)" >> $GITHUB_ENV
          git checkout ${{ env.HEAD_REF }}
          echo "HEAD_TOOLCHAIN_URL=$(cat .gcc_arm_none_eabi_url)" >> $GITHUB_ENV

      - name: Download toolchains
        run: |
          wget ${{ env.BASE_TOOLCHAIN_URL }}
          tar -xjf ${{ env.ARM_TOOLCHAIN_FILENAME }} && rm -rf ${{ env.ARM_TOOLCHAIN_FILENAME }}
          mv ${{ env.ARM_TOOLCHAIN_EXTRACT_DIRECTORY }} ~/base-toolchain

          wget ${{ env.HEAD_TOOLCHAIN_URL }}
          tar -xjf ${{ env.ARM_TOOLCHAIN_FILENAME }} && rm -rf ${{ env.ARM_TOOLCHAIN_FILENAME }}
          mv ${{ env.ARM_TOOLCHAIN_EXTRACT_DIRECTORY }} ~/head-toolchain

      - name: Add toolchain directory to path
        run: |
          tmp_home=$(echo ~)
          echo "$tmp_home/gcc-arm-none-eabi/bin" >> $GITHUB_PATH

      - name: Test ARM GCC Toolchain
        run: |
          ~/base-toolchain/bin/arm-none-eabi-gcc --version
          ~/head-toolchain/bin/arm-none-eabi-gcc --version

      - name: Create toolchain version variables
        id: create_toolchain_version_variables
        run: |
          tmp_home=$(echo ~)

          BASE_TOOLCHAIN_VERSION=$($tmp_home/base-toolchain/bin/arm-none-eabi-gcc --version | grep -Po '(?<=Toolchain ).*(?= \(re)' | sed 's/(G/G/g' | sed 's/)/ -/g')
          HEAD_TOOLCHAIN_VERSION=$($tmp_home/head-toolchain/bin/arm-none-eabi-gcc --version | grep -Po '(?<=Toolchain ).*(?= \(re)' | sed 's/(G/G/g' | sed 's/)/ -/g')

          echo "BASE_TOOLCHAIN_VERSION=$BASE_TOOLCHAIN_VERSION" >> $GITHUB_ENV
          echo "HEAD_TOOLCHAIN_VERSION=$HEAD_TOOLCHAIN_VERSION" >> $GITHUB_ENV

      #
      # Mark: - Config, compile
      #

      - name: Compile with base toolchain ${{ env.BASE_TOOLCHAIN_VERSION }}
        run: |
          git checkout ${{ env.BASE_REF }}
          mv ~/base-toolchain ~/gcc-arm-none-eabi
          make deep_clean
          make config
          make
          rm -rf ~/gcc-arm-none-eabi

      - name: Move base build artifacts to temporary directory
        run: |
          find _build ! -path '*CMakeFiles*' -name "*.bin" -print0 | xargs -0 -I {} cp {} _build_tmp/${{ env.BASE_SHA }}
          find _build ! -path '*CMakeFiles*' -name "*.map" -print0 | xargs -0 -I {} cp {} _build_tmp/${{ env.BASE_SHA }}
          find _build ! -path '*CMakeFiles*' -name "*.hex" -print0 | xargs -0 -I {} cp {} _build_tmp/${{ env.BASE_SHA }}
          find _build ! -path '*CMakeFiles*' -name "*.elf" -print0 | xargs -0 -I {} cp {} _build_tmp/${{ env.BASE_SHA }}

      - name: Compile with head toolchain ${{ env.HEAD_TOOLCHAIN_VERSION }}
        run: |
          git checkout ${{ env.HEAD_REF }}
          mv ~/head-toolchain ~/gcc-arm-none-eabi
          make deep_clean
          make config
          make
          rm -rf ~/gcc-arm-none-eabi

      - name: Move head build artifacts to temporary directory
        run: |
          find _build ! -path '*CMakeFiles*' -name "*.bin" -print0 | xargs -0 -I {} cp {} _build_tmp/${{ env.HEAD_SHA }}
          find _build ! -path '*CMakeFiles*' -name "*.map" -print0 | xargs -0 -I {} cp {} _build_tmp/${{ env.HEAD_SHA }}
          find _build ! -path '*CMakeFiles*' -name "*.hex" -print0 | xargs -0 -I {} cp {} _build_tmp/${{ env.HEAD_SHA }}
          find _build ! -path '*CMakeFiles*' -name "*.elf" -print0 | xargs -0 -I {} cp {} _build_tmp/${{ env.HEAD_SHA }}

      #
      # Mark: - Compare
      #

      - name: Compare bin files
        shell: bash
        run: |
          shopt -s xpg_echo

          echo 'STATUS_DIFF_OUTPUT<<EOF_STATUS_DIFF_OUTPUT' >> $GITHUB_ENV

          base_targets=($(echo $(find _build_tmp/${{ env.BASE_SHA }} -name '*.bin' -execdir basename -s '.bin' {} +) | tr ' ' '\n' | sort -du | tr '\n' ' '))
          head_targets=($(echo $(find _build_tmp/${{ env.HEAD_SHA }} -name '*.bin' -execdir basename -s '.bin' {} +) | tr ' ' '\n' | sort -du | tr '\n' ' '))
          all_targets=($(echo "${base_targets[@]} ${head_targets[@]}" | tr ' ' '\n' | sort -du | tr '\n' ' '))

          echo "Set added/deleted targets"
          added_targets=()
          deleted_targets=()
          for target in "${all_targets[@]}"; do
            if [[ ${base_targets[*]} =~ "$target" ]] && ! [[ ${head_targets[*]} =~ "$target" ]]; then
              deleted_targets+=($target)
            elif ! [[ ${base_targets[*]} =~ "$target" ]] && [[ ${head_targets[*]} =~ "$target" ]]; then
              added_targets+=($target)
            fi
          done

          echo "all:     ${all_targets[*]}"
          echo "base:    ${base_targets[*]}"
          echo "head:    ${head_targets[*]}"
          echo "added:   ${added_targets[*]}"
          echo "deleted: ${deleted_targets[*]}"

          echo "| Target | Status | .bin | .map | Static RAM (base/head) | Static RAM Δ | Total Flash (base/head) | Total Flash Δ |" >> $GITHUB_ENV
          echo "|-------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|" >> $GITHUB_ENV

          for target in "${all_targets[@]}"; do
            target_name=$target

            echo -n "| $target_name " >> $GITHUB_ENV

            if [[ ${added_targets[*]} =~ "$target" ]]; then
              echo -n "| :sparkles: | - | - | - | - |\n" >> $GITHUB_ENV
            elif [[ ${deleted_targets[*]} =~ "$target" ]]; then
              echo -n "| :coffin: | - | - | - | - |\n" >> $GITHUB_ENV
            else
              echo -n "| :heavy_check_mark: " >> $GITHUB_ENV

              if ! output=$(diff _build_tmp/${{ env.BASE_SHA }}/$target_name.bin _build_tmp/${{ env.HEAD_SHA }}/$target_name.bin 2>/dev/null); then
                echo -n "| :x: " >> $GITHUB_ENV
              else
                echo -n "| :white_check_mark: " >> $GITHUB_ENV
              fi

              python3 extern/mbed-os/tools/memap.py -t GCC_ARM _build_tmp/${{ env.BASE_SHA }}/$target_name.map > _build_tmp/${{ env.BASE_SHA }}/$target_name.txt
              python3 extern/mbed-os/tools/memap.py -t GCC_ARM _build_tmp/${{ env.HEAD_SHA }}/$target_name.map > _build_tmp/${{ env.HEAD_SHA }}/$target_name.txt

              if ! output=$(diff _build_tmp/${{ env.BASE_SHA }}/$target_name.txt _build_tmp/${{ env.HEAD_SHA }}/$target_name.txt 2>/dev/null); then
                echo -n "| :x: " >> $GITHUB_ENV
              else
                echo -n "| :white_check_mark: " >> $GITHUB_ENV
              fi

              base_ram=$(grep -Po '(?<=\(data \+ bss\):\s)[[:digit:]]*' _build_tmp/${{ env.BASE_SHA }}/$target_name.txt)
              head_ram=$(grep -Po '(?<=\(data \+ bss\):\s)[[:digit:]]*' _build_tmp/${{ env.HEAD_SHA }}/$target_name.txt)
              diff_ram=$(($head_ram - $base_ram))

              if [ $diff_ram -lt 0 ]; then
                  diff_ram=":chart_with_downwards_trend: $diff_ram"
              elif [ $diff_ram -gt 0 ]; then
                  diff_ram=":chart_with_upwards_trend: $diff_ram"
              else
                  diff_ram="ø"
              fi

              base_flash=$(grep -Po '(?<=\(text \+ data\):\s)[[:digit:]]*' _build_tmp/${{ env.BASE_SHA }}/$target_name.txt)
              head_flash=$(grep -Po '(?<=\(text \+ data\):\s)[[:digit:]]*' _build_tmp/${{ env.HEAD_SHA }}/$target_name.txt)
              diff_flash=$(($head_flash - $base_flash))

              if [ $diff_flash -lt 0 ]; then
                  diff_flash=":chart_with_downwards_trend:  $diff_flash"
              elif [ $diff_flash -gt 0 ]; then
                  diff_flash=":chart_with_upwards_trend: $diff_flash"
              else
                  diff_flash="ø"
              fi

              echo -n "| $base_ram / $head_ram | $diff_ram | $base_flash / $head_flash | $diff_flash " >> $GITHUB_ENV

              echo -n "|\n" >> $GITHUB_ENV
            fi

          done

          echo 'EOF_STATUS_DIFF_OUTPUT' >> $GITHUB_ENV

      - name: Compare maps files
        shell: bash
        run: |
          shopt -s xpg_echo

          echo 'MAP_DIFF_OUTPUT<<EOF_MAP_DIFF_OUTPUT' >> $GITHUB_ENV

          base_targets=($(echo $(find _build_tmp/${{ env.BASE_SHA }} -name '*.bin' -execdir basename -s '.bin' {} +) | tr ' ' '\n' | sort -du | tr '\n' ' '))
          head_targets=($(echo $(find _build_tmp/${{ env.HEAD_SHA }} -name '*.bin' -execdir basename -s '.bin' {} +) | tr ' ' '\n' | sort -du | tr '\n' ' '))
          all_targets=($(echo "${base_targets[@]} ${head_targets[@]}" | tr ' ' '\n' | sort -du | tr '\n' ' '))

          echo "Set added/deleted targets"
          added_targets=()
          deleted_targets=()
          for target in "${all_targets[@]}"; do
            if [[ ${base_targets[*]} =~ "$target" ]] && ! [[ ${head_targets[*]} =~ "$target" ]]; then
              deleted_targets+=($target)
            elif ! [[ ${base_targets[*]} =~ "$target" ]] && [[ ${head_targets[*]} =~ "$target" ]]; then
              added_targets+=($target)
            fi
          done

          echo "all:     ${all_targets[*]}"
          echo "base:    ${base_targets[*]}"
          echo "head:    ${head_targets[*]}"
          echo "added:   ${added_targets[*]}"
          echo "deleted: ${deleted_targets[*]}"

          no_map_diff=true

          for target in "${all_targets[@]}"; do
            target_name=$target

            if ! [[ ${added_targets[*]} =~ "$target" ]] && ! [[ ${deleted_targets[*]} =~ "$target" ]]; then
              echo "$target not deleted nor new, running diff"

              if ! diff_output=$(diff --unified=150 _build_tmp/${{ env.BASE_SHA }}/$target_name.txt _build_tmp/${{ env.HEAD_SHA }}/$target_name.txt); then

                echo $diff_output

                echo "<details>" >> $GITHUB_ENV
                echo "<summary><b><code>$target_name</code></b> (click to expand)</summary>" >> $GITHUB_ENV
                echo "" >> $GITHUB_ENV

                echo "\`\`\`diff" >> $GITHUB_ENV
                echo "$diff_output" >> $GITHUB_ENV
                echo "\`\`\`" >> $GITHUB_ENV

                echo "" >> $GITHUB_ENV
                echo "</details>" >> $GITHUB_ENV
                echo "" >> $GITHUB_ENV

                no_map_diff=false
              fi
            fi
          done

          if $no_map_diff; then
              echo "No differenes where found in map files." >> $GITHUB_ENV
          fi

          echo 'EOF_MAP_DIFF_OUTPUT' >> $GITHUB_ENV

      - name: Publish differences
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: analysis_toolchain
          recreate: true
          message: |
            #  Toolchain upgrade analysis report

            ## Versions :bookmark:

            - base: [`${{ env.BASE_REF }}`](https://github.com/leka/LekaOS/tree/${{ env.BASE_REF }}) / ${{ env.BASE_SHA }} + `${{ env.BASE_MBED_VERSION }}` + `${{ env.BASE_CXX_STANDARD }}`
            - base toolchain: `${{ env.BASE_TOOLCHAIN_VERSION }}`
            - head: [`${{ env.HEAD_REF }}`](https://github.com/leka/LekaOS/tree/${{ env.HEAD_REF }}) / ${{ env.HEAD_SHA }} + `${{ env.HEAD_MBED_VERSION }}` + `${{ env.HEAD_CXX_STANDARD }}`
            - head toolchain: `${{ env.HEAD_TOOLCHAIN_VERSION }}`

            ## Summary :memo:

            <details>
            <summary>Click to show summary</summary>

            - :heavy_check_mark: - existing target
            - :sparkles: - new target
            - :coffin: - deleted target
            - :white_check_mark: - files are the same
            - :x: - files are different

            ${{ env.STATUS_DIFF_OUTPUT }}

            </details>

            ## Map files diff output :world_map:

            <details>
            <summary>Click to show diff list</summary>

            ${{ env.MAP_DIFF_OUTPUT }}

            </details>

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Toolchain-Upgrade-Build-Artifacts
          retention-days: 7
          path: |
            _build_tmp/${{ env.BASE_SHA }}/**/*.bin
            _build_tmp/${{ env.BASE_SHA }}/**/*.map
            _build_tmp/${{ env.BASE_SHA }}/**/*.hex
            _build_tmp/${{ env.BASE_SHA }}/**/*.elf
            _build_tmp/${{ env.HEAD_SHA }}/**/*.bin
            _build_tmp/${{ env.HEAD_SHA }}/**/*.map
            _build_tmp/${{ env.HEAD_SHA }}/**/*.hex
            _build_tmp/${{ env.HEAD_SHA }}/**/*.elf
