# Leka - LekaOS
# Copyright 2022 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Functional Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_functional_tests:
    name: Build & Test
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          brew update && brew upgrade
          brew unlink arm-gcc-bin@10
          brew install --force --overwrite arm-gcc-bin@13
          brew link --force --overwrite arm-gcc-bin@13
          python3 -m pip install -U --user -r ./tools/config/mbed_requirements.txt --break-system-packages
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1

      - name: Config & Build
        run: |
          make deep_clean
          make pull_deps
          make config
          make

      - name: Run functional tests
        run: |
          python3 -u tools/run_functional_tests.py --all
