# Leka - LekaOS
# Copyright 2022 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Functional Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_functional_tests:
    name: Build & Test
    runs-on: [self-hosted, robot]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #
      # Mark: - Config & Build
      #

      - name: Config & Build
        run: |
          make deep_clean
          make pull_deps
          make config
          make

      #
      # Mark: - Run functional tests
      #

      - name: Run functional tests
        run: |
          python3 -u tools/run_functional_tests.py --all
