# Leka - LekaOS
# Copyright 2024 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: System Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_system_tests:
    name: Build & Test
    runs-on: robot

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          brew update && brew upgrade
          brew upgrade arm-gcc-bin
          python3 -m pip install -U --user -r ./tools/config/mbed_requirements.txt

      #
      # Mark: - Config & Build
      #

      - name: Config & Build
        run: |
          make deep_clean
          make pull_deps
          make config
          make

      #
      # Mark: - Run system tests
      #

      - name: Run system tests
        run: |
          python3 -u tools/run_system_tests.py --duration 800 --deep-sleep-percentage 1
