# CI Workflow

name: CI

on: [push]
  paths-ignore:
  - 'docs/**'
  - 'extern/**'
  - 'tools/**'
  - '.vscode/**'
  - '.editorconfig'
  - '.gitignore'
  - '.mbed'
  - 'LICENSE'
  - 'README.md'

jobs:

  make_config_make_all:
    name: Config & Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Brew install coreutils & ninja
        run: |
          brew install coreutils ninja
          echo "/usr/local/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
      - name: Brew install arm-none-eabi-gcc
        run: |
          brew tap ArmMbed/homebrew-formulae
          brew install arm-none-eabi-gcc
      - name: Clone Mbed OS
        run: |
          make clone_mbed BRANCH=mbed-os-6.3.0
      - name: Install mbed-cli and dependencies
        run: |
          python3 -m pip install -U --user mbed-cli pyserial intelhex prettytable
          python3 -m pip install -U --user -r extern/mbed-os/requirements.txt
      - name: Config build system
        run: |
          make config
      - name: Build LekaOS & al.
        run: |
          make

  clang_format_check:
    name: Clang Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.10
        with:
          source: './src ./lib ./spike ./test'
          exclude: './extern'
          extensions: 'h,cpp,c'
          clangFormatVersion: 10
          inplace: "" # meaning false, see https://github.com/DoozyX/clang-format-lint-action/issues/18#issue-710169130
