# Leka - LekaOS
# Copyright 2021 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: "Compare base/head changes"
description: ""

inputs:
  comment_header:
    description: "Specify comment header if needed"
    required: true

  enable_log_debug:
    description: "ENABLE_LOG_DEBUG=[ON, OFF]"
    required: true

  base_dir:
    description: "Path to base files"
    required: true

  head_dir:
    description: "Path to head files"
    required: true

runs:
  using: "composite"
  steps:
    - name: Compare changes
      id: compare_base_head_changes
      shell: bash
      run: ${{ github.action_path }}/compare_base_head_files.sh ${{ inputs.base_dir }} ${{ inputs.head_dir }}

    - name: Generate statistics
      id: generate_statistics
      shell: bash
      run: ${{ github.action_path }}/generate_statistics.sh ${{ inputs.base_dir }} ${{ inputs.head_dir }}

    - name: Get diffs
      id: get_diffs
      shell: bash
      run: ${{ github.action_path }}/get_diffs.sh ${{ inputs.base_dir }} ${{ inputs.head_dir }}

    - name: Create stick message
      id: create_sticky_message
      shell: bash
      run: ruby ${{ github.action_path }}/generate_sticky_note.rb
      env:
        RUNNER_HOME: ${{ env.RUNNER_HOME }}
        ENABLE_LOG_DEBUG: ${{ inputs.enable_log_debug }}
        ARM_GNU_TOOLCHAIN_VERSION: ${{ env.TOOLCHAIN_VERSION  }}
        BASE_REF: ${{ env.BASE_REF }}
        HEAD_REF: ${{ env.HEAD_REF }}
        BASE_SHA: ${{ env.BASE_SHA }}
        HEAD_SHA: ${{ env.HEAD_SHA }}
        BASE_MBED_VERSION: ${{ env.BASE_MBED_VERSION }}
        HEAD_MBED_VERSION: ${{ env.HEAD_MBED_VERSION }}
        BASE_CXX_STANDARD: ${{ env.BASE_CXX_STANDARD }}
        HEAD_CXX_STANDARD: ${{ env.HEAD_CXX_STANDARD }}

    - name: Publish differences
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        header: compare_base_head_changes-${{ inputs.comment_header }}
        path: ${{ env.RUNNER_HOME }}/STICKY_MESSAGE.md
